-- Generated from Detalle de 7 productos The Mens Formula.xlsx. Do not edit product rows by hand; regenerate this migration before it is applied.

create extension if not exists pgcrypto;

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  image_url text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.brands (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  logo_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  short_description text,
  category_id uuid not null references public.categories(id),
  brand_id uuid not null references public.brands(id),
  price numeric(12, 2),
  sku text unique,
  stock integer,
  sale_price numeric(12, 2),
  cost numeric(12, 2),
  featured boolean not null default false,
  is_new boolean not null default false,
  color text,
  model text,
  specifications jsonb not null default '{}'::jsonb,
  main_image_url text,
  is_active boolean not null default true,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  image_url text not null,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (product_id, sort_order)
);

create index if not exists products_catalog_index on public.products (is_active, is_available, category_id, brand_id);
create index if not exists products_slug_index on public.products (slug);
create index if not exists product_images_product_index on public.product_images (product_id, sort_order);

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path = public as $$ begin new.updated_at = now(); return new; end; $$;

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at before update on public.categories for each row execute function public.set_updated_at();
drop trigger if exists brands_set_updated_at on public.brands;
create trigger brands_set_updated_at before update on public.brands for each row execute function public.set_updated_at();
drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();

alter table public.categories enable row level security;
alter table public.brands enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;

create policy "Public can read active categories" on public.categories for select to anon, authenticated using (is_active);
create policy "Public can read active brands" on public.brands for select to anon, authenticated using (is_active);
create policy "Public can read active products" on public.products for select to anon, authenticated using (is_active);
create policy "Public can read product images" on public.product_images for select to anon, authenticated using (exists (select 1 from public.products where products.id = product_images.product_id and products.is_active));

grant select on public.categories, public.brands, public.products, public.product_images to anon, authenticated;

insert into storage.buckets (id, name, public) values ('products', 'products', true) on conflict (id) do update set public = excluded.public;
create policy "Public can view product media" on storage.objects for select to anon, authenticated using (bucket_id = 'products');

insert into public.categories (slug, name, description, sort_order) values
  ('after-shave', 'After shave', 'Productos para finalizar el afeitado.', 1),
  ('afeitado', 'Afeitado', 'Productos para un rasurado preciso.', 2),
  ('productos-para-cabello', 'Productos para cabello', 'Fijación, volumen y cuidado capilar.', 3),
  ('productos-para-barba', 'Productos para barba', 'Cuidado y definición para barba y bigote.', 4),
  ('cuidado-facial', 'Cuidado facial', 'Limpieza y preparación de la piel.', 5),
  ('talcos', 'Talcos', 'Acabados profesionales para barbería.', 6),
  ('accesorios', 'Accesorios', 'Complementos para el servicio profesional.', 7)
on conflict (slug) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;

insert into public.brands (name, slug) values
  ('Level3', 'level3'),
  ('Immortal', 'immortal'),
  ('Agiva', 'agiva'),
  ('4x4', '4x4'),
  ('Evok', 'evok'),
  ('Xiomara', 'xiomara'),
  ('Catrin', 'catrin')
on conflict (slug) do update set name = excluded.name;

insert into public.products (name, slug, description, short_description, category_id, brand_id, price, main_image_url, is_active, is_available) values
  ('After Shave MIDNIGHT', 'level3-after-shave-midnight', 'Fragancia MIDNIGHT con notas de limón, menta y verbena de la India. Ideal para finalizar el afeitado dejando una sensación fresca y perfumada.', 'Fragancia MIDNIGHT con notas de limón, menta y verbena de la India. Ideal para finalizar el afeitado dejando una sensación fresca y perfumada.', (select id from categories where slug = 'after-shave'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-after-shave-midnight.webp', true, true),
  ('After Shave FRESH', 'level3-after-shave-fresh', 'Fragancia FRESH con notas de bergamota de Calabria y pimienta. Ayuda a calmar la piel después del afeitado y deja un aroma limpio y elegante.', 'Fragancia FRESH con notas de bergamota de Calabria y pimienta. Ayuda a calmar la piel después del afeitado y deja un aroma limpio y elegante.', (select id from categories where slug = 'after-shave'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-after-shave-fresh.webp', true, true),
  ('After Shave FROST', 'level3-after-shave-frost', 'Fragancia FROST con notas de nuez moscada, vainilla, bayas de enebro y maderas ambaradas. Aporta frescura y una terminación aromática intensa.', 'Fragancia FROST con notas de nuez moscada, vainilla, bayas de enebro y maderas ambaradas. Aporta frescura y una terminación aromática intensa.', (select id from categories where slug = 'after-shave'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-after-shave-frost.webp', true, true),
  ('After Shave ROYALE', 'level3-after-shave-royale', 'Fragancia ROYALE con notas de pomelo, jengibre, ambrox y cítricos. Ideal para completar el servicio de afeitado con un aroma moderno y sofisticado.', 'Fragancia ROYALE con notas de pomelo, jengibre, ambrox y cítricos. Ideal para completar el servicio de afeitado con un aroma moderno y sofisticado.', (select id from categories where slug = 'after-shave'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-after-shave-royale.webp', true, true),
  ('After Shave AQUA', 'level3-after-shave-aqua', 'Fragancia AQUA con notas de pomelo, limón, menta y pimienta rosa. Brinda una sensación fresca y revitalizante después del afeitado.', 'Fragancia AQUA con notas de pomelo, limón, menta y pimienta rosa. Brinda una sensación fresca y revitalizante después del afeitado.', (select id from categories where slug = 'after-shave'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-after-shave-aqua.webp', true, true),
  ('After Shave VIBRANT', 'level3-after-shave-vibrant', 'Fragancia VIBRANT con notas verdes, pomelo, especias, bergamota, lavanda y petitgrain. Deja la piel suave, fresca y agradablemente perfumada.', 'Fragancia VIBRANT con notas verdes, pomelo, especias, bergamota, lavanda y petitgrain. Deja la piel suave, fresca y agradablemente perfumada.', (select id from categories where slug = 'after-shave'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-after-shave-vibrant.webp', true, true),
  ('After Shave ROSÉ', 'level3-after-shave-rose', 'Fragancia ROSÉ con notas de maracuyá, melocotón y frambuesa. Ofrece un aroma frutal y fresco para finalizar el afeitado.', 'Fragancia ROSÉ con notas de maracuyá, melocotón y frambuesa. Ofrece un aroma frutal y fresco para finalizar el afeitado.', (select id from categories where slug = 'after-shave'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-after-shave-rose.webp', true, true),
  ('Shaving Gel AQUA', 'level3-shaving-gel-aqua', 'Su fórmula permite ver claramente la zona de trabajo, lubrica e hidrata la piel y ayuda a reducir la irritación y los pequeños cortes. Fragancia AQUA.', 'Su fórmula permite ver claramente la zona de trabajo, lubrica e hidrata la piel y ayuda a reducir la irritación y los pequeños cortes. Fragancia AQUA.', (select id from categories where slug = 'afeitado'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-shaving-gel-aqua.webp', true, true),
  ('Shaving Gel ICE', 'level3-shaving-gel-ice', 'Facilita el deslizamiento de la cuchilla, protege e hidrata la piel y permite delineados precisos al mantener visible la zona de afeitado. Fragancia ICE.', 'Facilita el deslizamiento de la cuchilla, protege e hidrata la piel y permite delineados precisos al mantener visible la zona de afeitado. Fragancia ICE.', (select id from categories where slug = 'afeitado'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-shaving-gel-ice.webp', true, true),
  ('Black Mask', 'level3-black-mask', 'Ayuda a retirar puntos negros, suciedad, células muertas y exceso de grasa. Limpia los poros y deja la piel más suave, limpia y fresca.', 'Ayuda a retirar puntos negros, suciedad, células muertas y exceso de grasa. Limpia los poros y deja la piel más suave, limpia y fresca.', (select id from categories where slug = 'cuidado-facial'), (select id from brands where slug = 'level3'), 90, '/catalogo/level3/level3-black-mask.webp', true, true),
  ('Pink Mask', 'level3-pink-mask', 'Ayuda a remover impurezas y puntos negros, absorbe el exceso de grasa y favorece una apariencia más limpia, equilibrada y luminosa.', 'Ayuda a remover impurezas y puntos negros, absorbe el exceso de grasa y favorece una apariencia más limpia, equilibrada y luminosa.', (select id from categories where slug = 'cuidado-facial'), (select id from brands where slug = 'level3'), 90, '/catalogo/level3/level3-pink-mask.webp', true, true),
  ('Shampoo 2en 1', 'level3-shampoo-2en-1', 'Ayuda a suavizar, controlar el frizz y mejorar el brillo y la manejabilidad del cabello. Apto para todo tipo de cabello y práctico para uso profesional o en casa.', 'Ayuda a suavizar, controlar el frizz y mejorar el brillo y la manejabilidad del cabello. Apto para todo tipo de cabello y práctico para uso profesional o en casa.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'level3'), 120, '/catalogo/level3/level3-shampoo-2en-1.webp', true, true),
  ('Tinted Gel', 'level3-tinted-gel', 'Proporciona color negro de aspecto natural, fijación fuerte, volumen, textura y brillo. Fórmula a base de agua, sin escamas y fácil de retirar con el lavado.', 'Proporciona color negro de aspecto natural, fijación fuerte, volumen, textura y brillo. Fórmula a base de agua, sin escamas y fácil de retirar con el lavado.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-tinted-gel.webp', true, true),
  ('Styling powder', 'level3-styling-powder', 'Se aplica directamente en raíces o cabello seco para crear textura y elevar el cabello sin necesidad de productos pesados. Ideal para estilos con volumen y acabado natural.', 'Se aplica directamente en raíces o cabello seco para crear textura y elevar el cabello sin necesidad de productos pesados. Ideal para estilos con volumen y acabado natural.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'level3'), 110, '/catalogo/level3/level3-styling-powder.webp', true, true),
  ('Pomade', 'level3-pomade', 'Ideal para peinados clásicos o pulidos. Permite moldear y dar definición al cabello, proporcionando fijación y un acabado brillante de apariencia profesional.', 'Ideal para peinados clásicos o pulidos. Permite moldear y dar definición al cabello, proporcionando fijación y un acabado brillante de apariencia profesional.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-pomade.webp', true, true),
  ('Forming Cream', 'level3-forming-cream', 'Aporta volumen y textura sin dejar el cabello rígido o pegajoso. Su consistencia ligera permite remodelar el peinado y funciona especialmente bien en cabello fino o delgado.', 'Aporta volumen y textura sin dejar el cabello rígido o pegajoso. Su consistencia ligera permite remodelar el peinado y funciona especialmente bien en cabello fino o delgado.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-forming-cream.webp', true, true),
  ('Paste', 'level3-paste', 'Aporta textura, definición y volumen sin brillo. Su fórmula a base de agua es fácil de aplicar, permite retocar el estilo y se enjuaga sin dejar residuos.', 'Aporta textura, definición y volumen sin brillo. Su fórmula a base de agua es fácil de aplicar, permite retocar el estilo y se enjuaga sin dejar residuos.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-paste.webp', true, true),
  ('Spider wax', 'level3-spider-wax', 'Su efecto fibroso facilita moldear estilos texturizados con control flexible. Ideal para marcar mechones, aportar estructura y crear acabados modernos.', 'Su efecto fibroso facilita moldear estilos texturizados con control flexible. Ideal para marcar mechones, aportar estructura y crear acabados modernos.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-spider-wax.webp', true, true),
  ('Brillant Cream', 'level3-brillant-cream', 'Ofrece fijación duradera con flexibilidad para remodelar el cabello. Su textura suave ayuda a mejorar la definición y el brillo sin dejar residuos visibles.', 'Ofrece fijación duradera con flexibilidad para remodelar el cabello. Su textura suave ayuda a mejorar la definición y el brillo sin dejar residuos visibles.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-brillant-cream.webp', true, true),
  ('Matte Putty', 'level3-matte-putty', 'Aporta volumen suave, textura ligera y control flexible. Mantiene el cabello manejable y permite ajustar el peinado durante el día sin sensación pegajosa ni brillo.', 'Aporta volumen suave, textura ligera y control flexible. Mantiene el cabello manejable y permite ajustar el peinado durante el día sin sensación pegajosa ni brillo.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'level3'), 99, '/catalogo/level3/level3-matte-putty.webp', true, true),
  ('Hair Gel', 'level3-hair-gel', 'Aporta definición, volumen y control sin sensación grasosa. Fórmula a base de agua y sin escamas, fácil de lavar y adecuada para estilos estructurados.', 'Aporta definición, volumen y control sin sensación grasosa. Fórmula a base de agua y sin escamas, fácil de lavar y adecuada para estilos estructurados.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'level3'), 75, '/catalogo/level3/level3-hair-gel.webp', true, true),
  ('Cream Gel', 'level3-cream-gel', 'Ayuda a nutrir y proteger el cabello mientras aporta volumen, definición y control. Fórmula a base de agua, sin escamas y adecuada para definir rizos o estilos con brillo natural.', 'Ayuda a nutrir y proteger el cabello mientras aporta volumen, definición y control. Fórmula a base de agua, sin escamas y adecuada para definir rizos o estilos con brillo natural.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'level3'), 75, '/catalogo/level3/level3-cream-gel.webp', true, true),
  ('Mud Scrub Mask', 'level3-mud-scrub-mask', 'Con arcilla de caolín y extracto de manzanilla. Ayuda a retirar suciedad, exceso de grasa, impurezas, células muertas y puntos negros, dejando la piel más limpia y luminosa.', 'Con arcilla de caolín y extracto de manzanilla. Ayuda a retirar suciedad, exceso de grasa, impurezas, células muertas y puntos negros, dejando la piel más limpia y luminosa.', (select id from categories where slug = 'cuidado-facial'), (select id from brands where slug = 'level3'), 120, '/catalogo/level3/level3-mud-scrub-mask.webp', true, true),
  ('Inmortal  Styling powder', 'immortal-inmortal-styling-powder', 'Ideal para crear textura, levantar la raíz y dar cuerpo al cabello sin aspecto húmedo. Se aplica en pequeñas cantidades sobre cabello seco y se moldea con los dedos.', 'Ideal para crear textura, levantar la raíz y dar cuerpo al cabello sin aspecto húmedo. Se aplica en pequeñas cantidades sobre cabello seco y se moldea con los dedos.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'immortal'), 105, '/catalogo/immortal/immortal-inmortal-styling-powder.webp', true, true),
  ('Inmortal Beard Care Srerum', 'immortal-inmortal-beard-care-srerum', 'Ayuda a mantener la barba más manejable y con aspecto cuidado, reduciendo la sensación de resequedad. Aplicar unas gotas y distribuir de raíz a puntas.', 'Ayuda a mantener la barba más manejable y con aspecto cuidado, reduciendo la sensación de resequedad. Aplicar unas gotas y distribuir de raíz a puntas.', (select id from categories where slug = 'productos-para-barba'), (select id from brands where slug = 'immortal'), 90, '/catalogo/immortal/immortal-inmortal-beard-care-srerum.webp', true, true),
  ('Inmortal Beard Pomade Wax', 'immortal-inmortal-beard-pomade-wax', 'Permite ordenar cabellos rebeldes, definir la forma y dar un acabado pulido sin necesidad de usar grandes cantidades. Trabajar entre las manos antes de aplicar.', 'Permite ordenar cabellos rebeldes, definir la forma y dar un acabado pulido sin necesidad de usar grandes cantidades. Trabajar entre las manos antes de aplicar.', (select id from categories where slug = 'productos-para-barba'), (select id from brands where slug = 'immortal'), 90, '/catalogo/immortal/immortal-inmortal-beard-pomade-wax.webp', true, true),
  ('Black Mask', 'immortal-black-mask', 'Ayuda a retirar impurezas, exceso de grasa y residuos superficiales, dejando una sensación de limpieza. Aplicar una capa uniforme evitando ojos, labios y zonas con vello.', 'Ayuda a retirar impurezas, exceso de grasa y residuos superficiales, dejando una sensación de limpieza. Aplicar una capa uniforme evitando ojos, labios y zonas con vello.', (select id from categories where slug = 'cuidado-facial'), (select id from brands where slug = 'immortal'), 85, '/catalogo/immortal/immortal-black-mask.webp', true, true),
  ('Shampoo Immortal INFUSE', 'immortal-shampoo-immortal-infuse', 'Limpia el cabello y el cuero cabelludo mientras ayuda a mantener suavidad y una apariencia fresca. Adecuado para el lavado habitual en barbería o en casa.', 'Limpia el cabello y el cuero cabelludo mientras ayuda a mantener suavidad y una apariencia fresca. Adecuado para el lavado habitual en barbería o en casa.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'immortal'), 95, '/catalogo/immortal/immortal-shampoo-immortal-infuse.webp', true, true),
  ('Shampoo Immortal Anti-Caspa', 'immortal-shampoo-immortal-anti-caspa', 'Limpia el cuero cabelludo y ayuda a controlar la acumulación visible de escamas y grasa. Usar con masaje suave y enjuagar completamente.', 'Limpia el cuero cabelludo y ayuda a controlar la acumulación visible de escamas y grasa. Usar con masaje suave y enjuagar completamente.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'immortal'), 95, '/catalogo/immortal/immortal-shampoo-immortal-anti-caspa.webp', true, true),
  ('Shampoo Immortal Anti-Caida de Cabello', 'immortal-shampoo-immortal-anti-caida-de-cabello', 'Proporciona limpieza del cabello y cuero cabelludo y está orientado a fortalecer la apariencia de la fibra capilar. Utilizar de acuerdo con las indicaciones del envase.', 'Proporciona limpieza del cabello y cuero cabelludo y está orientado a fortalecer la apariencia de la fibra capilar. Utilizar de acuerdo con las indicaciones del envase.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'immortal'), 95, '/catalogo/immortal/immortal-shampoo-immortal-anti-caida-de-cabello.webp', true, true),
  ('Shampoo Immortal 3 en 1', 'immortal-shampoo-immortal-3-en-1', 'Permite realizar la limpieza diaria en un solo producto, con enjuague fácil y sensación de frescura. Útil para casa, gimnasio o viaje.', 'Permite realizar la limpieza diaria en un solo producto, con enjuague fácil y sensación de frescura. Útil para casa, gimnasio o viaje.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'immortal'), 95, '/catalogo/immortal/immortal-shampoo-immortal-3-en-1.webp', true, true),
  ('Agiva 01 Orange', 'agiva-agiva-01-orange', 'Su textura facilita la distribución y el moldeado del cabello. Ideal para estilos pulidos que necesitan control y definición durante el día.', 'Su textura facilita la distribución y el moldeado del cabello. Ideal para estilos pulidos que necesitan control y definición durante el día.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'agiva'), 55, '/catalogo/agiva/agiva-agiva-01-orange.webp', true, true),
  ('Agiva 02 Blue', 'agiva-agiva-02-blue', 'Permite dar forma, definir y mantener el peinado con un acabado brillante. Aplicar una pequeña cantidad sobre cabello seco o ligeramente húmedo.', 'Permite dar forma, definir y mantener el peinado con un acabado brillante. Aplicar una pequeña cantidad sobre cabello seco o ligeramente húmedo.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'agiva'), 55, '/catalogo/agiva/agiva-agiva-02-blue.webp', true, true),
  ('Agiva 03 Green', 'agiva-agiva-03-green', 'Indicada para peinados naturales, texturizados o con volumen. Se trabaja fácilmente con los dedos y ayuda a mantener el estilo sin brillo marcado.', 'Indicada para peinados naturales, texturizados o con volumen. Se trabaja fácilmente con los dedos y ayuda a mantener el estilo sin brillo marcado.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'agiva'), 55, '/catalogo/agiva/agiva-agiva-03-green.webp', true, true),
  ('Agiva 04 Yellow', 'agiva-agiva-04-yellow', 'Se distribuye con facilidad y permite moldear distintos estilos, desde peinados clásicos hasta acabados más modernos. Se retira con lavado.', 'Se distribuye con facilidad y permite moldear distintos estilos, desde peinados clásicos hasta acabados más modernos. Se retira con lavado.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'agiva'), 55, '/catalogo/agiva/agiva-agiva-04-yellow.webp', true, true),
  ('Agiva 05 Red', 'agiva-agiva-05-red', 'Ayuda a mantener cabellos difíciles en su lugar y a crear peinados definidos y duraderos. Usar poca cantidad y distribuir uniformemente.', 'Ayuda a mantener cabellos difíciles en su lugar y a crear peinados definidos y duraderos. Usar poca cantidad y distribuir uniformemente.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'agiva'), 55, '/catalogo/agiva/agiva-agiva-05-red.webp', true, true),
  ('Agiva 06  Cream Wax', 'agiva-agiva-06-cream-wax', 'Su consistencia permite repartir el producto de forma uniforme, definir mechones y retocar el peinado durante la aplicación.', 'Su consistencia permite repartir el producto de forma uniforme, definir mechones y retocar el peinado durante la aplicación.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'agiva'), 55, '/catalogo/agiva/agiva-agiva-06-cream-wax.webp', true, true),
  ('Agiva 10 Grey (Tela de Araña)', 'agiva-agiva-10-grey-tela-de-arana', 'Al trabajarla entre las manos forma fibras que ayudan a repartir el producto, separar mechones y dar textura al peinado con un acabado moderno.', 'Al trabajarla entre las manos forma fibras que ayudan a repartir el producto, separar mechones y dar textura al peinado con un acabado moderno.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'agiva'), 55, '/catalogo/agiva/agiva-agiva-10-grey-tela-de-arana.webp', true, true),
  ('Agiva Styling Dust', 'agiva-agiva-styling-dust', 'Se aplica sobre cabello seco, especialmente en la raíz, para aumentar el cuerpo y facilitar el moldeado. Usar poco producto y añadir más si es necesario.', 'Se aplica sobre cabello seco, especialmente en la raíz, para aumentar el cuerpo y facilitar el moldeado. Usar poco producto y añadir más si es necesario.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'agiva'), 99, '/catalogo/agiva/agiva-agiva-styling-dust.webp', true, true),
  ('Shaving Gel', 'agiva-shaving-gel', 'Ayuda a lubricar e hidratar la piel durante el afeitado y permite ver el contorno mientras se trabaja. Aplicar una capa fina antes de pasar la navaja o rasuradora.', 'Ayuda a lubricar e hidratar la piel durante el afeitado y permite ver el contorno mientras se trabaja. Aplicar una capa fina antes de pasar la navaja o rasuradora.', (select id from categories where slug = 'afeitado'), (select id from brands where slug = 'agiva'), 89, '/catalogo/agiva/agiva-shaving-gel.webp', true, true),
  ('Cera Telaraña Aroma Chicle', '4x4-cera-telarana-aroma-chicle', 'Su textura fibrosa permite distribuir el producto entre los mechones y crear peinados definidos con movimiento. Ideal para acabados modernos y texturizados.', 'Su textura fibrosa permite distribuir el producto entre los mechones y crear peinados definidos con movimiento. Ideal para acabados modernos y texturizados.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = '4x4'), 60, '/catalogo/4x4/4x4-cera-telarana-aroma-chicle.webp', true, true),
  ('Cera Telaraña Aroma Banana', '4x4-cera-telarana-aroma-banana', 'Forma fibras al trabajarla con las manos, facilitando la definición de mechones y el control del peinado. Aplicar en pequeñas cantidades.', 'Forma fibras al trabajarla con las manos, facilitando la definición de mechones y el control del peinado. Aplicar en pequeñas cantidades.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = '4x4'), 60, '/catalogo/4x4/4x4-cera-telarana-aroma-banana.webp', true, true),
  ('Pasta 4x4 Profesional 100g', '4x4-pasta-4x4-profesional-100g', 'Adecuada para crear peinados definidos y trabajables. Distribuir una pequeña cantidad entre las manos y aplicar sobre cabello seco o ligeramente húmedo.', 'Adecuada para crear peinados definidos y trabajables. Distribuir una pequeña cantidad entre las manos y aplicar sobre cabello seco o ligeramente húmedo.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = '4x4'), 60, '/catalogo/4x4/4x4-pasta-4x4-profesional-100g.webp', true, true),
  ('Pomada 4x4 Profesional 100g', '4x4-pomada-4x4-profesional-100g', 'Ayuda a ordenar el cabello, definir líneas y mantener la forma del peinado. Ideal para estilos clásicos, laterales controlados y acabados de barbería.', 'Ayuda a ordenar el cabello, definir líneas y mantener la forma del peinado. Ideal para estilos clásicos, laterales controlados y acabados de barbería.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = '4x4'), 60, '/catalogo/4x4/4x4-pomada-4x4-profesional-100g.webp', true, true),
  ('Cera-Gel 4x4 Profesional 280g', '4x4-cera-gel-4x4-profesional-280g', 'Combina la manejabilidad de una cera con la aplicación de un gel, permitiendo crear estilos definidos y con buena presencia. Aplicar uniformemente sobre el cabello.', 'Combina la manejabilidad de una cera con la aplicación de un gel, permitiendo crear estilos definidos y con buena presencia. Aplicar uniformemente sobre el cabello.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = '4x4'), 75, '/catalogo/4x4/4x4-cera-gel-4x4-profesional-280g.webp', true, true),
  ('Enfriador para máquinas', '4x4-enfriador-para-maquinas', 'Ayuda a reducir la temperatura de la cuchilla entre servicios o durante jornadas continuas. Aplicar siguiendo las instrucciones del envase y evitando el contacto con la piel y los ojos.', 'Ayuda a reducir la temperatura de la cuchilla entre servicios o durante jornadas continuas. Aplicar siguiendo las instrucciones del envase y evitando el contacto con la piel y los ojos.', (select id from categories where slug = 'accesorios'), (select id from brands where slug = '4x4'), 95, '/catalogo/4x4/4x4-enfriador-para-maquinas.webp', true, true),
  ('Talco DORADO invensible 4x4 Profesional', '4x4-talco-dorado-invensible-4x4-profesional', 'Ayuda a absorber humedad y a retirar pequeños residuos de cabello, dejando una sensación seca y cómoda después del corte o afeitado.', 'Ayuda a absorber humedad y a retirar pequeños residuos de cabello, dejando una sensación seca y cómoda después del corte o afeitado.', (select id from categories where slug = 'talcos'), (select id from brands where slug = '4x4'), 55, '/catalogo/4x4/4x4-talco-dorado-invensible-4x4-profesional.webp', true, true),
  ('Shampoo CBD + Minoxidil', '4x4-shampoo-cbd-minoxidil', 'Limpia el cabello y el cuero cabelludo y está orientado al cuidado de cabellos que requieren una rutina fortalecedora. Utilizar únicamente según las indicaciones del envase.', 'Limpia el cabello y el cuero cabelludo y está orientado al cuidado de cabellos que requieren una rutina fortalecedora. Utilizar únicamente según las indicaciones del envase.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = '4x4'), 100, '/catalogo/4x4/4x4-shampoo-cbd-minoxidil.webp', true, true),
  ('Polvo Voluminizador seco', '4x4-polvo-voluminizador-seco', 'Ideal para elevar la raíz, dar cuerpo y mejorar el agarre del cabello sin apariencia húmeda. Aplicar poco a poco sobre cabello seco y moldear con los dedos.', 'Ideal para elevar la raíz, dar cuerpo y mejorar el agarre del cabello sin apariencia húmeda. Aplicar poco a poco sobre cabello seco y moldear con los dedos.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = '4x4'), 86, '/catalogo/4x4/4x4-polvo-voluminizador-seco.webp', true, true),
  ('Bálsamo negro líquido para aerógrafo', '4x4-balsamo-negro-liquido-para-aerografo', 'Permite sombrear, rellenar y marcar visualmente contornos de cabello o barba. Aplicar en capas ligeras y uniformes hasta lograr el efecto deseado.', 'Permite sombrear, rellenar y marcar visualmente contornos de cabello o barba. Aplicar en capas ligeras y uniformes hasta lograr el efecto deseado.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = '4x4'), 80, '/catalogo/4x4/4x4-balsamo-negro-liquido-para-aerografo.webp', true, true),
  ('Minoxidil Líquido 4X4', '4x4-minoxidil-liquido-4x4', 'Producto de uso externo. Aplicar únicamente conforme a la concentración, modo de uso y advertencias indicadas en el envase; evitar ojos y piel irritada.', 'Producto de uso externo. Aplicar únicamente conforme a la concentración, modo de uso y advertencias indicadas en el envase; evitar ojos y piel irritada.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = '4x4'), 100, '/catalogo/4x4/4x4-minoxidil-liquido-4x4.webp', true, true),
  ('Evoc "coco"', 'evok-evoc-coco', 'Ayuda a dar forma, brillo y control al peinado con una textura fácil de trabajar. Su aroma a coco aporta una sensación agradable durante el uso.', 'Ayuda a dar forma, brillo y control al peinado con una textura fácil de trabajar. Su aroma a coco aporta una sensación agradable durante el uso.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'evok'), 30, '/catalogo/evok/evok-evoc-coco.webp', true, true),
  ('Evoc "Fresa"', 'evok-evoc-fresa', 'Permite controlar y definir el peinado mientras aporta brillo y manejabilidad. Su aroma a fresa complementa el acabado del producto.', 'Permite controlar y definir el peinado mientras aporta brillo y manejabilidad. Su aroma a fresa complementa el acabado del producto.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'evok'), 30, '/catalogo/evok/evok-evoc-fresa.webp', true, true),
  ('Evoc "Manzana"', 'evok-evoc-manzana', 'Facilita la creación de estilos definidos, ayuda a controlar cabellos rebeldes y aporta un acabado brillante con aroma a manzana.', 'Facilita la creación de estilos definidos, ayuda a controlar cabellos rebeldes y aporta un acabado brillante con aroma a manzana.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'evok'), 30, '/catalogo/evok/evok-evoc-manzana.webp', true, true),
  ('Evoc "Sábila"', 'evok-evoc-sabila', 'Ofrece fijación y manejabilidad para distintos estilos, dejando el cabello definido y con buena apariencia. Se aplica en pequeñas cantidades.', 'Ofrece fijación y manejabilidad para distintos estilos, dejando el cabello definido y con buena apariencia. Se aplica en pequeñas cantidades.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'evok'), 30, '/catalogo/evok/evok-evoc-sabila.webp', true, true),
  ('Evoc "Negro"', 'evok-evoc-negro', 'Su textura permite moldear el cabello y mantener estilos bien estructurados. Ideal para peinados que requieren mayor control y acabado definido.', 'Su textura permite moldear el cabello y mantener estilos bien estructurados. Ideal para peinados que requieren mayor control y acabado definido.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'evok'), 35, '/catalogo/evok/evok-evoc-negro.webp', true, true),
  ('Evoc "Azul"', 'evok-evoc-azul', 'Ayuda a mantener el cabello en su lugar y facilita el moldeado de estilos clásicos o modernos. Aplicar una pequeña cantidad y distribuir uniformemente.', 'Ayuda a mantener el cabello en su lugar y facilita el moldeado de estilos clásicos o modernos. Aplicar una pequeña cantidad y distribuir uniformemente.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'evok'), 35, '/catalogo/evok/evok-evoc-azul.webp', true, true),
  ('Evoc "Blanco"', 'evok-evoc-blanco', 'Permite crear peinados definidos con buena manejabilidad y control. Puede aplicarse sobre cabello seco o ligeramente húmedo.', 'Permite crear peinados definidos con buena manejabilidad y control. Puede aplicarse sobre cabello seco o ligeramente húmedo.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'evok'), 35, '/catalogo/evok/evok-evoc-blanco.webp', true, true),
  ('Evoc "Rojo"', 'evok-evoc-rojo', 'Indicada para estilos que necesitan definición y control. Trabajar una pequeña cantidad entre las manos antes de distribuir en el cabello.', 'Indicada para estilos que necesitan definición y control. Trabajar una pequeña cantidad entre las manos antes de distribuir en el cabello.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'evok'), 35, '/catalogo/evok/evok-evoc-rojo.webp', true, true),
  ('After Shave Evok', 'evok-after-shave-evok', 'Ayuda a dejar una sensación fresca y una fragancia agradable al finalizar el servicio. Aplicar sobre piel limpia evitando ojos y zonas irritadas.', 'Ayuda a dejar una sensación fresca y una fragancia agradable al finalizar el servicio. Aplicar sobre piel limpia evitando ojos y zonas irritadas.', (select id from categories where slug = 'after-shave'), (select id from brands where slug = 'evok'), 59, '/catalogo/evok/evok-after-shave-evok.webp', true, true),
  ('Shaving Gel Evok', 'evok-shaving-gel-evok', 'Su transparencia permite visualizar los contornos mientras se afeita y ayuda a reducir la fricción de la cuchilla. Aplicar una capa uniforme antes del afeitado.', 'Su transparencia permite visualizar los contornos mientras se afeita y ayuda a reducir la fricción de la cuchilla. Aplicar una capa uniforme antes del afeitado.', (select id from categories where slug = 'afeitado'), (select id from brands where slug = 'evok'), 59, '/catalogo/evok/evok-shaving-gel-evok.webp', true, true),
  ('Tubo de Papel cuello color "Negro"', 'evok-tubo-de-papel-cuello-color-negro', 'Se coloca alrededor del cuello antes de la capa para mejorar la higiene y evitar el contacto directo con cabellos sueltos, productos o la tela de la capa.', 'Se coloca alrededor del cuello antes de la capa para mejorar la higiene y evitar el contacto directo con cabellos sueltos, productos o la tela de la capa.', (select id from categories where slug = 'accesorios'), (select id from brands where slug = 'evok'), 70, '/catalogo/evok/evok-tubo-de-papel-cuello-color-negro.webp', true, true),
  ('Tubo de Papel cuello color "Blanco"', 'evok-tubo-de-papel-cuello-color-blanco', 'Crea una barrera higiénica entre la piel y la capa de corte, ayudando a evitar el contacto con residuos de cabello y productos durante el servicio.', 'Crea una barrera higiénica entre la piel y la capa de corte, ayudando a evitar el contacto con residuos de cabello y productos durante el servicio.', (select id from categories where slug = 'accesorios'), (select id from brands where slug = 'evok'), 60, '/catalogo/evok/evok-tubo-de-papel-cuello-color-blanco.webp', true, true),
  ('Tela de araña Xiomara', 'xiomara-tela-de-arana-xiomara', 'Al trabajarla entre las manos forma fibras que facilitan la distribución, separación de mechones y creación de peinados con textura y movimiento.', 'Al trabajarla entre las manos forma fibras que facilitan la distribución, separación de mechones y creación de peinados con textura y movimiento.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'xiomara'), 45, '/catalogo/xiomara/xiomara-tela-de-arana-xiomara.webp', true, true),
  ('Cera moldeadora Xiomara', 'xiomara-cera-moldeadora-xiomara', 'Adecuada para distintos estilos de peinado; permite trabajar y ordenar el cabello aplicando una pequeña cantidad y distribuyéndola de manera uniforme.', 'Adecuada para distintos estilos de peinado; permite trabajar y ordenar el cabello aplicando una pequeña cantidad y distribuyéndola de manera uniforme.', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'xiomara'), 40, '/catalogo/xiomara/xiomara-cera-moldeadora-xiomara.webp', true, true),
  ('Minoxidil en Gel Marca "Catrin"', 'catrin-minoxidil-en-gel-marca-catrin', 'Catrin Gel de Crecimiento está diseñado para estimular los folículos y favorecer una barba con apariencia más densa y uniforme. Su fórmula incluye minoxidil, bergamota y gotu kola; algunas presentaciones también incorporan aloe vera, vitamina E y aceites nutritivos. Tiene textura en gel de fácil aplicación y rápida absorción', 'Catrin Gel de Crecimiento está diseñado para estimular los folículos y favorecer una barba con apariencia más densa y uniforme. Su fórmula incluye minoxidil, bergamota y gotu kola; algunas presentaciones también incorporan aloe vera, vitamina E y aceites nutritivos. Tiene textura en gel de fácil aplicación y rápida absorción', (select id from categories where slug = 'productos-para-cabello'), (select id from brands where slug = 'catrin'), 185, '/catalogo/catrin/catrin-minoxidil-en-gel-marca-catrin.webp', true, true)
on conflict (slug) do update set name = excluded.name, description = excluded.description, short_description = excluded.short_description, category_id = excluded.category_id, brand_id = excluded.brand_id, price = excluded.price, main_image_url = excluded.main_image_url, is_active = excluded.is_active, is_available = excluded.is_available;
